# Generated by Django 2.2.7 on 2019-11-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('courses', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('A', 'Provider A'),
                            ('B', 'Provider B'),
                            ('C', 'Provider C'),
                            ('YouTube', 'YouTube'),
                        ],
                        max_length=50,
                    ),
                ),
                ('url', models.URLField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'material',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='videos',
                        to='courses.Material',
                    ),
                ),
            ],
        )
    ]
