# Generated by Django 2.2.7 on 2019-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('courses', '0002_video')]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ranking',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3
            ),
        )
    ]
