# Generated by Django 2.2.7 on 2019-11-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('courses', '0004_comment')]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        )
    ]
