# Generated by Django 2.2.7 on 2019-11-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('courses', '0005_comment_likes')]

    operations = [
        migrations.AddField(
            model_name='course',
            name='badge',
            field=models.ImageField(null=True, upload_to='badges'),
        )
    ]
